### ISSUE TITLE
Stylish findability?

### ISSUE THREAD

**Issue by ylluminate** [StylishThemes/YouTube-Dark#1]
Is this findable through Stylish, the Safari extension?  I don't think I'm finding this there:
![screenshot](http://cl.ly/image/432I043i3G3d/Image%202015-06-27%20at%205.42.32%20PM.png)

**Comment by ddavison** [comment]
it's not searchable, no.. sorry about that.  i'll get to it eventually and upload it to the StylishThemes account.  In the meantime, it is relatively easy to install.
- go to https://travis-ci.org/StylishThemes/YouTube-Dark?branch=master
- find the point in the compilation where it says `$ cat ./stylesheets/youtube-dark.css`
- expand the `cat ...` statement, copy all the CSS, and create a new style targed at "youtube"

**Comment by ylluminate** [comment]
Thanks for the information.  You have done such a wonderful job on your dark themes.  Frankly I and a couple of others now ask ourselves how we ever used GitHub or StackOverflow without your work. :smiley_cat: Really appreciate your work!  I think you've inspired us to tackle a few other obscenely white sites by using your work as a base.

**Comment by ddavison** [comment]
glad to hear it! if you do end up creating a couple, we wouldn't mind adding your repo to stylishthemes and adding you to the team.

thanks for the love :+1:
